import type { Metadata } from "next";
import type { Area } from "./areas";

/** Canonical production origin (see wrangler.jsonc custom domain). */
export const SITE_URL = "https://dirtbikes.typearson.dev";
export const SITE_NAME = "SoCal Dirt Bike Field Guide";
/** Build-time share card generated by app/opengraph-image.tsx. */
export const OG_IMAGE_PATH = "/opengraph-image";

/**
 * Per-area page metadata. The page supplies its hand-written `title` (without a
 * brand suffix — the root layout's title template appends that) and
 * `description`; this adds the canonical URL and a matching Open Graph block so
 * every area page is consistent and links share cleanly.
 */
export function areaMetadata(
  area: Area,
  { title, description }: { title: string; description: string },
): Metadata {
  const path = `/${area.id}`;
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title: `${title} — ${SITE_NAME}`,
      description,
      url: path,
      type: "article",
      // Nested routes don't inherit the root opengraph-image convention, so
      // point at the generated share card explicitly.
      images: [OG_IMAGE_PATH],
    },
    twitter: { images: [OG_IMAGE_PATH] },
  };
}
