// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const bigBearRoutes: Route[] = [
  {
    "id": "pinyon-vista",
    "name": "Cactus Flat OHV Singletrack",
    "forestRoad": "2E20.1, 2E20.2, 2E20.3, 2E20.4, 2E20.5",
    "summary": "Big Bear's designated OHV trail tread, narrow-gauge, not a fire road.",
    "description": "The 2E20 system is the designated OHV trail network off the upper Cactus Flat / Smarts Ranch road (3N03), in the pinyon and juniper north of Baldwin Lake. Narrow, wheeled-OHV tread under 50 inches, sandy with rocky sections, the closest thing in the area to true singletrack and the one featured ride here that's open to green-sticker dirt bikes the whole way.",
    "distanceMiles": 6.4,
    "difficulty": "Moderate",
    "elevationFt": "6,000–6,300 ft",
    "surface": "Narrow OHV tread (≤50 in.), sandy with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 2E20.1 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated OHV trail, not a fire road",
      "Fully green-sticker (wheeled OHV under 50 inches)",
      "Pinyon-and-juniper country north of Baldwin Lake"
    ],
    "trailhead": {
      "name": "Cactus Flat OHV Singletrack (2E20.1)",
      "lat": 34.2976,
      "lng": -116.7952
    }
  },
  {
    "id": "holcomb-valley",
    "name": "Holcomb Valley Loop",
    "forestRoad": "3N16",
    "summary": "Historic gold-rush basin with mellow, flowing dirt road riding.",
    "description": "Looping through the old Holcomb Valley mining district north of Big Bear Lake, this is mostly wide, graded forest road with gentle grades and pine-shaded meadows. A great warm-up or family-friendly route with plenty of historic stops like Belleville and the Hangman's Tree.",
    "distanceMiles": 21.9,
    "difficulty": "Easy",
    "elevationFt": "5,500–7,650 ft",
    "surface": "Graded dirt road with occasional washboard",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Holcomb Valley Loop is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Historic gold-mining sites and interpretive markers",
      "Open meadows and easy navigation",
      "Connects to many other Big Bear backcountry roads"
    ],
    "trailhead": {
      "name": "Holcomb Valley Loop (3N16)",
      "lat": 34.3037,
      "lng": -116.8226
    }
  },
  {
    "id": "gold-mountain",
    "name": "Gold Mountain / Dishpan Springs",
    "forestRoad": "3N69",
    "summary": "Scenic climb past old mines to wide high-desert overlooks.",
    "description": "A technical climb up the flanks of Gold Mountain with mixed dirt and rocky pitches, passing relics of the area's mining past. The upper sections open to sweeping views across Baldwin Lake and the high desert toward Lucerne Valley.",
    "distanceMiles": 4.5,
    "difficulty": "Difficult",
    "elevationFt": "6,750–8,200 ft",
    "surface": "Dirt road with loose rock and rutted climbs",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 3N69 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Big views over Baldwin Lake and the desert",
      "Historic mine sites",
      "Links the John Bull area"
    ],
    "trailhead": {
      "name": "Gold Mountain / Dishpan Springs (3N69)",
      "lat": 34.2992,
      "lng": -116.8373
    }
  },
  {
    "id": "cactus-flats",
    "name": "Cactus Flat OHV Area",
    "forestRoad": "3N03",
    "summary": "East-side OHV staging hub feeding the area's road network.",
    "description": "Off Highway 18 north of Big Bear, Cactus Flat is a designated OHV staging area (vault toilet, parking, signage) feeding Smarts Ranch Rd (3N03) through pinyon and juniper. Terrain ranges from easy dirt road to looser, sandier routes.",
    "distanceMiles": 7.3,
    "difficulty": "Moderate",
    "elevationFt": "5,900–6,800 ft",
    "surface": "Mixed dirt and sandy tread with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Cactus Flat OHV Area is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Established OHV staging and parking",
      "Green-sticker access on part of the road",
      "High-desert transition scenery"
    ],
    "trailhead": {
      "name": "Cactus Flat OHV Area (3N03)",
      "lat": 34.315,
      "lng": -116.8106
    }
  },
  {
    "id": "coxey-road",
    "name": "Coxey Road Connector",
    "forestRoad": "3N14",
    "summary": "Long, mellow graded road, the backbone of the backcountry.",
    "description": "Coxey Road runs from Fawnskin toward the northern forest boundary. Smooth and beginner-friendly with long sight lines, it's ideal for building seat time or covering ground between trail systems.",
    "distanceMiles": 10.5,
    "difficulty": "Easy",
    "elevationFt": "5,650–7,200 ft",
    "surface": "Wide graded dirt, generally smooth",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Coxey Road Connector is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Great for beginners and warm-ups",
      "Central connector to the northern road network",
      "Forest and meadow scenery"
    ],
    "trailhead": {
      "name": "Coxey Road Connector (3N14)",
      "lat": 34.2837,
      "lng": -116.9646
    }
  },
  {
    "id": "van-dusen-canyon",
    "name": "Van Dusen Canyon Road",
    "forestRoad": "3N09",
    "summary": "Historic stage road, an easy, scenic climb from town toward Holcomb Valley.",
    "description": "A wide, smooth dirt road following the old Van Dusen Canyon stage route from Big Bear City up to Holcomb Valley. Gentle and beginner-friendly under a canopy of pines, one of the most accessible ways into the backcountry.",
    "distanceMiles": 3.5,
    "difficulty": "Easy",
    "elevationFt": "6,850–7,400 ft",
    "surface": "Wide, smooth graded dirt",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 3N09 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Historic Van Dusen stage route",
      "Gentle, beginner-friendly grade",
      "Direct line into Holcomb Valley"
    ],
    "trailhead": {
      "name": "Van Dusen Canyon Road (3N09)",
      "lat": 34.2719,
      "lng": -116.8544
    }
  },
  {
    "id": "arrastre-creek",
    "name": "Arrastre Creek Road",
    "forestRoad": "2N02",
    "summary": "Long east-side graded road with one green-sticker stretch.",
    "description": "Arrastre Creek Road runs from Baldwin Lake Road east toward the forest boundary, climbing through Jeffrey pine and high-desert transition. A scenic, moderate ride, mostly plate-only, with one segment open to all vehicles.",
    "distanceMiles": 10.5,
    "difficulty": "Moderate",
    "elevationFt": "6,300–7,100 ft",
    "surface": "Graded dirt with rocky, rutted sections",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Arrastre Creek Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long, scenic east-side mileage",
      "Jeffrey pine and high-desert transition",
      "Quieter than the OHV staging areas"
    ],
    "trailhead": {
      "name": "Arrastre Creek Road (2N02)",
      "lat": 34.2795,
      "lng": -116.7962
    }
  },
  {
    "id": "john-bull",
    "name": "John Bull Trail",
    "forestRoad": "3N10",
    "summary": "Big Bear's most famous trail, a brutal experts-only rock crawl that's more bragging rights than flow on a bike.",
    "description": "One of the most famous technical trails in Southern California, John Bull is a relentless field of granite boulders and step-ups. The Forest Service rates it black-diamond / most difficult. On a dirt bike it demands expert balance, line choice, and clutch control, and most riders find it more punishing than fun. Ranked low here because it's plate-only and a sufferfest on two wheels, not because it isn't famous. Never ride it alone.",
    "distanceMiles": 5.6,
    "difficulty": "Expert",
    "elevationFt": "7,300–8,150 ft",
    "surface": "Large granite boulders and rock ledges",
    "bestSeason": "June–September",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 3N10 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Iconic technical rock obstacles",
      "Big payoff views from the high desert edge",
      "Connects to the Gold Mountain network"
    ],
    "trailhead": {
      "name": "John Bull Trail (3N10)",
      "lat": 34.319,
      "lng": -116.8545
    }
  }
];
