// AUTO-GENERATED by scripts/build-blm-routes.mjs — do not edit by hand.
// Geometry & access: BLM GTLF travel network. Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const elPasoRoutes: Route[] = [
  {
    "id": "el-paso-singletrack",
    "name": "El Paso Mountains Singletrack",
    "summary": "A real moto singletrack network threading the volcanic badlands.",
    "description": "The El Paso Mountains hold one of the better designated singletrack networks in the Ridgecrest desert: miles of narrow motorcycle-only tread twisting through colorful volcanic country, tight and sandy with rocky pitches. For most riders this, not the roads, is the point of coming out here. The line on the map joins the area's designated single-track segments so you can see roughly where the network runs.",
    "distanceMiles": 19.4,
    "difficulty": "Difficult",
    "elevationFt": "2,800–4,350 ft",
    "surface": "Narrow motorcycle-only singletrack, sandy and rocky",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, this is designated motorized single-track open to motorcycles, so green-sticker (non-street-legal) bikes are allowed; it's moto-width only, no ATVs or wider machines. Stay on the designated tread. Registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Designated motorcycle-only singletrack",
      "Colorful volcanic badlands country",
      "The best dirt-bike riding in the El Pasos"
    ],
    "trailhead": {
      "name": "El Paso Mountains Singletrack",
      "lat": 35.4683,
      "lng": -117.728
    }
  },
  {
    "id": "el-paso-willis-well",
    "name": "Willis Well Road",
    "forestRoad": "R43",
    "summary": "A long designated open route across the El Paso backcountry.",
    "description": "R43 (Willis Well Road) is one of the longer designated open routes through the El Paso Mountains, natural-surface desert two-track running across the benches and washes past old wells and mining ground. Sandy stretches trade off with rockier pitches, real backcountry mileage well off the staging areas. Open and green-sticker the length of it.",
    "distanceMiles": 9.7,
    "difficulty": "Moderate",
    "elevationFt": "2,200–4,100 ft",
    "surface": "Natural-surface desert two-track, sand and rock",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, Willis Well Road is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. The BLM designation carries a limitation (closed to ohv recreation. limited to designated county roads and highways, and all routes needed to provide access for established easements, administrative access, emergency access, and other permitted uses), so check the route signs. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Long designated open route, real seat time",
      "Old wells and mining country",
      "Quiet El Paso backcountry"
    ],
    "trailhead": {
      "name": "Willis Well Road",
      "lat": 35.3898,
      "lng": -117.7727
    }
  },
  {
    "id": "el-paso-black-mountain",
    "name": "Black Mountain Road",
    "summary": "Designated route climbing toward Black Mountain.",
    "description": "Black Mountain Road is a designated open route working up toward Black Mountain on the north side of the range, a natural-surface climb with rockier high-clearance pitches and expanding views over the desert and the Sierra to the west. A solid intermediate ride that connects into the wider El Paso network.",
    "distanceMiles": 6.3,
    "difficulty": "Moderate",
    "elevationFt": "3,050–3,500 ft",
    "surface": "Natural-surface high-clearance dirt, rocky up high",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, Black Mountain Road is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Climbs toward Black Mountain",
      "Big desert and Sierra views",
      "Connects the El Paso route network"
    ],
    "trailhead": {
      "name": "Black Mountain Road",
      "lat": 35.5009,
      "lng": -117.9489
    }
  },
  {
    "id": "el-paso-iron-canyon",
    "name": "Iron Canyon",
    "summary": "Short, scenic canyon route into the El Paso badlands.",
    "description": "Iron Canyon is a short designated route threading one of the colorful eroded canyons that make the El Pasos worth the drive, sandy in the wash bottom with rockier benches and striking volcanic rock. A scenic add-on rather than a destination on its own, best paired with the longer routes and the singletrack.",
    "distanceMiles": 2.4,
    "difficulty": "Moderate",
    "elevationFt": "2,900–3,650 ft",
    "surface": "Sandy canyon bottom with rocky benches",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, Iron Canyon is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Colorful eroded volcanic canyon",
      "Sandy-wash riding",
      "Pairs with the El Paso network"
    ],
    "trailhead": {
      "name": "Iron Canyon",
      "lat": 35.4302,
      "lng": -117.6793
    }
  }
];
