// AUTO-GENERATED by scripts/build-blm-routes.mjs — do not edit by hand.
// Geometry & access: BLM GTLF travel network. Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const jawboneRoutes: Route[] = [
  {
    "id": "jawbone-singletrack",
    "name": "Jawbone Motorized Singletrack",
    "summary": "The designated motorcycle singletrack the area is really known for.",
    "description": "Beyond the roads, Jawbone carries a network of designated motorized singletrack: narrow, twisting motorcycle-only tread through the desert that's the real reason dirt-bikers come here. Tight, sandy, and technical in spots, it's true singletrack, not a two-track, and it's strictly motorcycle width. This entry stitches the area's designated singletrack segments into one line so you can see where it runs.",
    "distanceMiles": 3.3,
    "difficulty": "Difficult",
    "elevationFt": "3,900–4,400 ft",
    "surface": "Narrow motorcycle-only singletrack, sandy and technical",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, this is designated motorized singletrack open to motorcycles, so green-sticker (non-street-legal) bikes are allowed; it's motorcycle width only, no ATVs or wider machines. Stay on the designated tread. Registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Designated motorcycle-only singletrack",
      "The real draw for dirt-bikers here",
      "Tight, sandy, technical desert tread"
    ],
    "trailhead": {
      "name": "Jawbone Motorized Singletrack",
      "lat": 35.2544,
      "lng": -118.143
    }
  },
  {
    "id": "jawbone-canyon-road",
    "name": "Jawbone Canyon Road",
    "summary": "The main artery up Jawbone Canyon from Highway 14 into the OHV network.",
    "description": "Jawbone Canyon Road is the way in: a graded sand and gravel route running west off Highway 14 up the canyon, past the old aqueduct siphon pipe, into the heart of the Jawbone OHV area. It's the staging spine that the rest of the network branches off, easy going on its own and the natural warm-up for a day out here.",
    "distanceMiles": 4.8,
    "difficulty": "Easy",
    "elevationFt": "2,650–4,700 ft",
    "surface": "Graded sand and gravel canyon road",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, Jawbone Canyon Road is a designated open route, so green-sticker (non-street-legal) bikes are allowed. This is open OHV land: stay on designated routes, registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Primary access from Highway 14",
      "Passes the landmark aqueduct siphon pipe",
      "Connects the whole Jawbone OHV network"
    ],
    "trailhead": {
      "name": "Jawbone Canyon Road",
      "lat": 35.3632,
      "lng": -118.1132
    }
  },
  {
    "id": "sc-103-east",
    "name": "SC-103 East",
    "forestRoad": "SC-103",
    "summary": "A long designated route working east across the Jawbone backcountry.",
    "description": "SC-103 is one of the longer designated routes in the area, miles of natural-surface two-track winding through Joshua tree and creosote on the high benches above the canyon. Sandy washes give way to rockier climbs and back again. It runs well out past the staging areas, so it's a quieter ride than the canyon, and it's green-sticker the whole way.",
    "distanceMiles": 13.4,
    "difficulty": "Moderate",
    "elevationFt": "2,850–5,300 ft",
    "surface": "Natural-surface desert two-track, sand and rock",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, SC-103 East is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Miles of high-desert two-track",
      "Joshua tree and creosote benches",
      "Quieter than the canyon staging areas"
    ],
    "trailhead": {
      "name": "SC-103 East",
      "lat": 35.4526,
      "lng": -118.1003
    }
  },
  {
    "id": "sc-94",
    "name": "SC-94",
    "forestRoad": "SC-94",
    "summary": "Designated open desert route threading the benches above the canyon.",
    "description": "SC-94 is a shorter designated route of natural-surface two-track linking the Jawbone benches, sandy straights broken up by rockier pitches. It ties into the rest of the SC network, so it's an easy piece to fold into a bigger loop rather than a destination on its own.",
    "distanceMiles": 6.4,
    "difficulty": "Moderate",
    "elevationFt": "3,550–4,350 ft",
    "surface": "Natural-surface two-track, sandy with rocky sections",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, SC-94 is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Green-sticker desert two-track",
      "Ties into the SC network for a loop",
      "Sandy straights and rocky pitches"
    ],
    "trailhead": {
      "name": "SC-94",
      "lat": 35.4347,
      "lng": -118.0163
    }
  },
  {
    "id": "butterbredt-canyon",
    "name": "Butterbredt Canyon Road",
    "summary": "Sandy canyon route toward Butterbredt Spring on the north side of the area.",
    "description": "Butterbredt Canyon Road runs up its namesake canyon toward Butterbredt Spring, a sandy, scenic route on the quieter north side of the complex toward the Piute Mountains. The spring is a well-known desert oasis and migratory bird stop, so it's a mellower, prettier ride than the open flats, sandy in the wash bottoms with firmer benches.",
    "distanceMiles": 2.1,
    "difficulty": "Moderate",
    "elevationFt": "4,450–5,050 ft",
    "surface": "Sandy canyon bottom with firmer benches",
    "bestSeason": "October–April (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the BLM travel plan, Butterbredt Canyon Road is a designated route open to motorized use, so green-sticker (non-street-legal) bikes are allowed. Stay on designated routes; registration + spark arrestor required.",
      "source": "BLM Ground Transportation Linear Features (GTLF), 2026"
    },
    "highlights": [
      "Toward the Butterbredt Spring oasis",
      "Quieter north side near the Piute Mountains",
      "Scenic sandy canyon riding"
    ],
    "trailhead": {
      "name": "Butterbredt Canyon Road",
      "lat": 35.4595,
      "lng": -118.2102
    }
  }
];
