// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const lagunaRoutes: Route[] = [
  {
    "id": "corral-canyon",
    "name": "Corral Canyon Road",
    "forestRoad": "17S04",
    "summary": "The namesake road of San Diego's Corral Canyon OHV Area.",
    "description": "17S04 is the spine of the Corral Canyon OHV Area near Pine Valley, a rocky, high-clearance road through chaparral and oak with technical pitches and connections to the area's trail network. It's open to all vehicles on its OHV segments and highway-legal-only on others, so green-sticker access is segment-by-segment; read the signs at each junction.",
    "distanceMiles": 8.2,
    "difficulty": "Difficult",
    "elevationFt": "3,050–3,850 ft",
    "surface": "Rocky, high-clearance OHV-area dirt",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Corral Canyon Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Heart of the Corral Canyon OHV Area",
      "Green-sticker access on part of the road",
      "Rocky, technical San Diego backcountry"
    ],
    "trailhead": {
      "name": "Corral Canyon Road (17S04)",
      "lat": 32.7103,
      "lng": -116.5202
    }
  },
  {
    "id": "bear-valley",
    "name": "Bear Valley Road",
    "forestRoad": "16S12",
    "summary": "Rugged OHV-area road through the Corral Canyon backcountry.",
    "description": "16S12 (Bear Valley) is a rugged high-clearance road in the Corral Canyon country, mixing rocky climbs and oak-shaded canyon bottoms. Part of it is open to all vehicles, so green-sticker access is segment-by-segment, a solid intermediate-to-hard ride that links the OHV-area roads.",
    "distanceMiles": 8.4,
    "difficulty": "Difficult",
    "elevationFt": "3,200–4,600 ft",
    "surface": "Rocky high-clearance dirt",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Bear Valley Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Rocky Corral Canyon backcountry",
      "Connects the OHV-area network"
    ],
    "trailhead": {
      "name": "Bear Valley Road (16S12)",
      "lat": 32.817,
      "lng": -116.5328
    }
  },
  {
    "id": "skye-valley",
    "name": "Skye Valley Road",
    "forestRoad": "17S06",
    "summary": "OHV-area road threading the Skye Valley chaparral.",
    "description": "17S06 (Skye Valley) runs through the chaparral and grassland of the Corral Canyon area, a mix of graded and rockier tread. Part of it is open to all vehicles, so green-sticker access is segment-by-segment, a good intermediate green-sticker option in the network.",
    "distanceMiles": 7.9,
    "difficulty": "Moderate",
    "elevationFt": "2,900–3,850 ft",
    "surface": "Graded-to-rocky OHV-area dirt",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Skye Valley Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Chaparral-and-grassland scenery",
      "Links the Corral Canyon roads"
    ],
    "trailhead": {
      "name": "Skye Valley Road (17S06)",
      "lat": 32.725,
      "lng": -116.5593
    }
  },
  {
    "id": "long-valley-loop",
    "name": "Long Valley Loop",
    "forestRoad": "16S15",
    "summary": "Fully green-sticker loop in the Corral Canyon OHV Area.",
    "description": "16S15 (Long Valley Loop) is a designated open-to-all-vehicles loop in the Corral Canyon OHV Area, the cleanest green-sticker ride here, with rocky and sandy tread through oak and chaparral. A fun, self-contained loop that's a natural centerpiece for a green-sticker day.",
    "distanceMiles": 4.5,
    "difficulty": "Moderate",
    "elevationFt": "3,800–4,100 ft",
    "surface": "Rocky and sandy OHV-area tread",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 16S15 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Fully designated green-sticker loop",
      "Centerpiece of the OHV-area network",
      "Oak-and-chaparral San Diego backcountry"
    ],
    "trailhead": {
      "name": "Long Valley Loop (16S15)",
      "lat": 32.7594,
      "lng": -116.5074
    }
  },
  {
    "id": "los-pinos",
    "name": "Los Pinos Road",
    "forestRoad": "16S17",
    "summary": "Climb toward the Los Pinos lookout above Corral Canyon.",
    "description": "16S17 climbs toward the Los Pinos fire lookout on the ridge above the Corral Canyon area, a high-clearance road with rocky sections and expanding views over the San Diego backcountry to the desert. Part of it is open to all vehicles, so green-sticker access is segment-by-segment.",
    "distanceMiles": 4.6,
    "difficulty": "Moderate",
    "elevationFt": "3,850–4,650 ft",
    "surface": "Rocky high-clearance dirt",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Los Pinos Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Climbs toward the Los Pinos lookout",
      "Green-sticker access on part of the road",
      "Big San-Diego-to-desert views"
    ],
    "trailhead": {
      "name": "Los Pinos Road (16S17)",
      "lat": 32.7525,
      "lng": -116.5729
    }
  },
  {
    "id": "kernan-trail",
    "name": "Kernan Trail",
    "forestRoad": "802",
    "summary": "The longest singletrack in the Corral Canyon OHV Area.",
    "description": "Trail 802 (Kernan) is the longest dedicated OHV trail in the Corral Canyon system near Pine Valley, narrow, rocky, twisting singletrack through dense chaparral and oak. This is the real reason riders come to Corral Canyon: technical green-sticker trail riding, not fire roads. Open to vehicles 50 inches and under.",
    "distanceMiles": 5.5,
    "difficulty": "Difficult",
    "elevationFt": "3,100–4,050 ft",
    "surface": "Narrow, rocky OHV singletrack",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 802 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Longest singletrack in the Corral Canyon system",
      "Technical, narrow OHV trail",
      "Designated green-sticker singletrack"
    ],
    "trailhead": {
      "name": "Kernan Trail (802)",
      "lat": 32.7246,
      "lng": -116.5591
    }
  },
  {
    "id": "wrangler-trail",
    "name": "Wrangler Trail",
    "forestRoad": "901",
    "summary": "Classic Corral Canyon OHV singletrack loop trail.",
    "description": "Trail 901 (Wrangler) is one of the signature OHV trails in the Corral Canyon network, a twisting green-sticker singletrack through chaparral that links the area's loop system. Tighter and more technical than the roads, it's prime dirt-bike trail riding, open to vehicles 50 inches and under.",
    "distanceMiles": 3.6,
    "difficulty": "Moderate",
    "elevationFt": "3,450–3,950 ft",
    "surface": "Narrow OHV singletrack, rocky and sandy",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 901 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Signature Corral Canyon trail",
      "Twisting green-sticker singletrack",
      "Links the area's loop system"
    ],
    "trailhead": {
      "name": "Wrangler Trail (901)",
      "lat": 32.6932,
      "lng": -116.5545
    }
  },
  {
    "id": "peace-maker-trail",
    "name": "Peace Maker Singletrack",
    "forestRoad": "912",
    "summary": "Motorcycle-only singletrack in the Corral Canyon OHV Area.",
    "description": "Trail 912 (Peace Maker) is designated open to motorcycles only, true narrow-gauge singletrack, the tightest, most technical green-sticker riding in the Corral Canyon system. No quads or wider machines; just dirt bikes threading the chaparral. The heart of why Corral Canyon is San Diego's best forest moto-trail area.",
    "distanceMiles": 2.6,
    "difficulty": "Difficult",
    "elevationFt": "3,300–3,650 ft",
    "surface": "Tight motorcycle-only singletrack",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 912 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Motorcycle-only singletrack",
      "Tightest, most technical trail here",
      "Designated green-sticker (dirt bikes only)"
    ],
    "trailhead": {
      "name": "Peace Maker Singletrack (912)",
      "lat": 32.7073,
      "lng": -116.5973
    }
  },
  {
    "id": "la-posta",
    "name": "La Posta Road",
    "forestRoad": "15S05",
    "summary": "Long plated forest road on the south side of the Lagunas.",
    "description": "15S05 (La Posta) is a long graded forest road through the oak and chaparral country south of the Laguna crest, a scenic plated dual-sport ride. Highway-legal-only, it's a good way to cover ground and link the area's backcountry away from the OHV roads.",
    "distanceMiles": 10.9,
    "difficulty": "Moderate",
    "elevationFt": "3,400–6,050 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 15S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long, scenic plated dual-sport road",
      "Oak-and-chaparral Laguna country",
      "Quieter than the OHV area"
    ],
    "trailhead": {
      "name": "La Posta Road (15S05)",
      "lat": 32.8564,
      "lng": -116.4232
    }
  },
  {
    "id": "pine-creek",
    "name": "Pine Creek Road",
    "forestRoad": "14S05",
    "summary": "Mellow plated road below the Laguna crest near Pine Valley.",
    "description": "14S05 (Pine Creek) is a gentler graded road near Pine Valley below the Laguna Mountain crest, a relaxed plated ride through pine and oak good for building seat time and reaching the area's trailheads. Highway-legal only.",
    "distanceMiles": 7.7,
    "difficulty": "Easy",
    "elevationFt": "3,700–5,400 ft",
    "surface": "Wide graded dirt, generally smooth",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 14S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Easy, beginner-friendly grade",
      "Pine-and-oak Laguna foothills",
      "Trailhead access near Pine Valley (plated only)"
    ],
    "trailhead": {
      "name": "Pine Creek Road (14S05)",
      "lat": 32.8506,
      "lng": -116.525
    }
  }
];
