// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const lakeArrowheadRoutes: Route[] = [
  {
    "id": "crab-flats-road",
    "name": "Crab Flats Road",
    "forestRoad": "3N34",
    "summary": "The hub of the Crab Flats green-sticker network near Green Valley Lake.",
    "description": "3N34 runs through the Crab Flats area between Green Valley Lake and the Deep Creek country, the staging hub for this corner of the forest. Graded dirt with rockier, rutted stretches through pine and cedar, linking the campground to the OHV roads and trails around it. Part of it is open to all vehicles and part is open to street-legal vehicles only, so green-sticker access depends on the segment.",
    "distanceMiles": 12,
    "difficulty": "Moderate",
    "elevationFt": "4,400–5,950 ft",
    "surface": "Graded dirt with rocky, rutted sections",
    "bestSeason": "May–November (snow closes it in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Crab Flats Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Staging hub for the Crab Flats OHV network",
      "Green-sticker access on part of the road",
      "Pine-and-cedar country near Green Valley Lake"
    ],
    "trailhead": {
      "name": "Crab Flats Road (3N34)",
      "lat": 34.2607,
      "lng": -117.0845
    }
  },
  {
    "id": "deep-creek-singletrack",
    "name": "Deep Creek OHV Singletrack",
    "forestRoad": "2W01",
    "summary": "Designated motorcycle singletrack in the Deep Creek country.",
    "description": "Trail 2W01 is a designated motorcycle trail threading the slopes above Deep Creek, narrow green-sticker singletrack with rocky, twisting tread well off the fire roads. This is the kind of riding people come to this side of the forest for: true singletrack, motorcycles only, not a graded road. Short, but it pairs naturally with the Crab Flats roads for a real green-sticker day.",
    "distanceMiles": 2.8,
    "difficulty": "Difficult",
    "elevationFt": "4,250–4,900 ft",
    "surface": "Narrow, rocky motorcycle singletrack",
    "bestSeason": "May–November (snow closes it in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 2W01 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated motorcycle-only singletrack",
      "Above the Deep Creek drainage",
      "True green-sticker trail, not a fire road"
    ],
    "trailhead": {
      "name": "Deep Creek OHV Singletrack (2W01)",
      "lat": 34.325,
      "lng": -117.1213
    }
  },
  {
    "id": "cleghorn-ridge",
    "name": "Cleghorn Ridge OHV Road",
    "forestRoad": "2N47",
    "summary": "Long green-sticker ridge road above Silverwood Lake, about 15 miles.",
    "description": "2N47 runs the Cleghorn Ridge above Silverwood Lake and the Cajon Pass, roughly 15 miles open to all vehicles the length of its OHV stretch. That makes it the rare thing on a dirt bike: a long green-sticker ride, not just a short spur. Rocky, high-clearance tread along an exposed chaparral ridge with big views down to the lake and out over the pass, well away from the Crab Flats crowds.",
    "distanceMiles": 14.7,
    "difficulty": "Moderate",
    "elevationFt": "3,050–5,300 ft",
    "surface": "Rocky, high-clearance ridge dirt",
    "bestSeason": "Year-round (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 2N47 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "About 15 miles of designated green-sticker road",
      "Views over Silverwood Lake and Cajon Pass",
      "Exposed chaparral ridge riding"
    ],
    "trailhead": {
      "name": "Cleghorn Ridge OHV Road (2N47)",
      "lat": 34.3005,
      "lng": -117.3369
    }
  },
  {
    "id": "miller-canyon",
    "name": "Miller Canyon OHV Road",
    "forestRoad": "2N37",
    "summary": "Short green-sticker road dropping through Miller Canyon.",
    "description": "2N37 follows Miller Canyon as a road open to all vehicles, a compact green-sticker option with sandy canyon-bottom stretches and rockier benches through chaparral on the slopes below Crab Flats. A quick, scenic ride and a natural add-on to a bigger green-sticker day in the area rather than a destination on its own.",
    "distanceMiles": 4.3,
    "difficulty": "Moderate",
    "elevationFt": "3,650–5,050 ft",
    "surface": "Sandy canyon bottom with rocky benches",
    "bestSeason": "Year-round (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 2N37 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated green-sticker road",
      "Sandy canyon-bottom character",
      "Pairs with the Crab Flats network"
    ],
    "trailhead": {
      "name": "Miller Canyon OHV Road (2N37)",
      "lat": 34.2701,
      "lng": -117.2903
    }
  },
  {
    "id": "pilot-rock-road",
    "name": "Pilot Rock Road",
    "forestRoad": "2N33",
    "summary": "Long ridge road between Lake Arrowhead and Silverwood, partly green-sticker.",
    "description": "2N33 works the ridge between the Lake Arrowhead crest and Silverwood Lake past the Pilot Rock landmark, a long high-clearance road with rocky, rutted climbs and long views in both directions. Part of it is open to all vehicles and part is open to street-legal vehicles only, so green-sticker access shifts from one segment to the next.",
    "distanceMiles": 11.2,
    "difficulty": "Moderate",
    "elevationFt": "3,400–5,150 ft",
    "surface": "High-clearance dirt with rocky, rutted climbs",
    "bestSeason": "Year-round (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Pilot Rock Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long ridge between Arrowhead and Silverwood",
      "Green-sticker access on part of the road",
      "Pilot Rock landmark and big two-way views"
    ],
    "trailhead": {
      "name": "Pilot Rock Road (2N33)",
      "lat": 34.2854,
      "lng": -117.2194
    }
  },
  {
    "id": "bailey-canyon",
    "name": "Bailey Canyon Road",
    "forestRoad": "2N49",
    "summary": "Long, remote plated backcountry road on the west side of the area.",
    "description": "2N49 pushes a long way through the Bailey Canyon backcountry on the Silverwood / Cleghorn side, roughly 16 miles of rough, high-clearance road through remote chaparral and oak. It's open to street-legal vehicles only, so it's a plated dual-sport ride: quiet, committing, and a good way to cover ground away from the OHV staging areas. Carry water and go prepared.",
    "distanceMiles": 16.3,
    "difficulty": "Difficult",
    "elevationFt": "2,100–5,550 ft",
    "surface": "Long, rough high-clearance backcountry dirt",
    "bestSeason": "Spring and fall (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 2N49 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "About 16 miles of remote backcountry",
      "Quiet plated dual-sport riding",
      "Chaparral-and-oak Silverwood country"
    ],
    "trailhead": {
      "name": "Bailey Canyon Road (2N49)",
      "lat": 34.2084,
      "lng": -117.3506
    }
  }
];
