// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const mtPinosRoutes: Route[] = [
  {
    "id": "alamo-mountain",
    "name": "Alamo Mountain OHV",
    "forestRoad": "8N01.3",
    "summary": "High green-sticker loop around 8,000-foot Alamo Mountain.",
    "description": "8N01.3 is the OHV-designated upper loop around Alamo Mountain, climbing toward 8,000 feet through pine forest in the headwaters of Piru Creek. A long, rocky, high-clearance green-sticker road with big high-country views — the marquee OHV ride of the Mt Pinos / Frazier Park complex. Snow closes it seasonally up high.",
    "distanceMiles": 13.5,
    "difficulty": "Difficult",
    "elevationFt": "4,750–7,050 ft",
    "surface": "Rocky, high-clearance OHV-area dirt",
    "bestSeason": "May–October (seasonal snow closure)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 8N01.3 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Loops 8,000-foot Alamo Mountain",
      "Pine high country in the Piru headwaters",
      "Marquee green-sticker ride of the area"
    ],
    "trailhead": {
      "name": "Alamo Mountain OHV (8N01.3)",
      "lat": 34.6878,
      "lng": -118.9337
    }
  },
  {
    "id": "mutau",
    "name": "Mutau OHV Road",
    "forestRoad": "7N03.2",
    "summary": "Long, remote green-sticker road toward Mutau Flat.",
    "description": "7N03 (Mutau) runs deep toward Mutau Flat on the edge of the Sespe backcountry, a long open-to-all-vehicles road mixing forest and meadow with sandy and rocky stretches. Remote, quiet green-sticker mileage — go prepared; seasonal.",
    "distanceMiles": 9.9,
    "difficulty": "Moderate",
    "elevationFt": "4,750–5,750 ft",
    "surface": "Mixed forest road, sandy and rocky sections",
    "bestSeason": "May–October (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 7N03.2 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Remote ride toward Mutau Flat",
      "Edge of the Sespe backcountry",
      "Quiet green-sticker mileage"
    ],
    "trailhead": {
      "name": "Mutau OHV Road (7N03.2)",
      "lat": 34.704,
      "lng": -119.1218
    }
  },
  {
    "id": "apache-canyon",
    "name": "Apache Canyon OHV",
    "forestRoad": "8N06",
    "summary": "Green-sticker road through the colorful Cuyama badlands.",
    "description": "8N06 threads Apache Canyon in the sandstone badlands on the Cuyama side of the range, an open-to-all-vehicles road with sandy washes, rocky benches, and striking eroded rock. A fun, scenic green-sticker ride that pairs with neighboring Quatal Canyon.",
    "distanceMiles": 8.9,
    "difficulty": "Moderate",
    "elevationFt": "3,300–4,450 ft",
    "surface": "Sandy wash and rocky badlands tread",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 8N06 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Colorful Cuyama sandstone badlands",
      "Sandy-wash green-sticker riding",
      "Pairs with Quatal Canyon"
    ],
    "trailhead": {
      "name": "Apache Canyon OHV (8N06)",
      "lat": 34.7482,
      "lng": -119.4085
    }
  },
  {
    "id": "quatal-canyon",
    "name": "Quatal Canyon OHV",
    "forestRoad": "9N09.2",
    "summary": "Sandstone-badlands OHV road — green-sticker on part of it.",
    "description": "Quatal Canyon (9N09) is the classic Cuyama-badlands sand-wash ride, winding through dramatic eroded sandstone. Part of it is designated open to all vehicles and part is highway-legal-only, so green-sticker access is segment-by-segment — read the signs at each junction. Sandy and exposed; best in cool weather.",
    "distanceMiles": 9.9,
    "difficulty": "Moderate",
    "elevationFt": "3,550–5,750 ft",
    "surface": "Deep sandy wash through sandstone badlands",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Quatal Canyon OHV is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only — so access is segment-by-segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Dramatic sandstone badlands",
      "Sandy-wash riding",
      "Green-sticker access on part of the road"
    ],
    "trailhead": {
      "name": "Quatal Canyon OHV (9N09.2)",
      "lat": 34.8363,
      "lng": -119.3829
    }
  },
  {
    "id": "frazier-mountain",
    "name": "Frazier Mountain OHV",
    "forestRoad": "8N04.2",
    "summary": "Green-sticker climb to the Frazier Mountain lookout.",
    "description": "8N04.2 is the OHV-designated climb up Frazier Mountain toward the lookout and summit antennas near 8,000 feet, with sweeping views over Lockwood Valley, Mt Pinos, and the high desert. A rocky, high-clearance green-sticker road; seasonal up top.",
    "distanceMiles": 4.2,
    "difficulty": "Moderate",
    "elevationFt": "6,250–8,000 ft",
    "surface": "Rocky, high-clearance climb",
    "bestSeason": "May–October (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 8N04.2 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Climbs toward the Frazier Mountain lookout",
      "Views over Lockwood Valley and Mt Pinos",
      "Designated green-sticker road"
    ],
    "trailhead": {
      "name": "Frazier Mountain OHV (8N04.2)",
      "lat": 34.7844,
      "lng": -119.003
    }
  },
  {
    "id": "scott-russell",
    "name": "Scott Russell OHV",
    "forestRoad": "9N21.1, 9N21.2, 9N21.3",
    "summary": "Green-sticker OHV road in the Frazier high country.",
    "description": "9N21 (Scott Russell) is an open-to-all-vehicles road in the forested country between Frazier Mountain and Lockwood Valley, mixing graded and rockier stretches through pine and oak. A solid intermediate green-sticker ride linking the area's OHV network; seasonal.",
    "distanceMiles": 5.1,
    "difficulty": "Moderate",
    "elevationFt": "5,350–7,150 ft",
    "surface": "Mixed graded and rocky forest road",
    "bestSeason": "May–October (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 9N21.1 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Forested Frazier high country",
      "Links the area's OHV network",
      "Designated green-sticker road"
    ],
    "trailhead": {
      "name": "Scott Russell OHV (9N21.1)",
      "lat": 34.8252,
      "lng": -119.0116
    }
  },
  {
    "id": "mt-pinos-singletrack",
    "name": "Mt Pinos Singletrack",
    "forestRoad": "19W04",
    "summary": "Long designated motorcycle singletrack — the area's premier trail ride.",
    "description": "Trail 19W04 is one of the longest designated motorcycle trails in the Mt Pinos area — miles of narrow, technical green-sticker singletrack winding through the backcountry well away from the OHV roads. This is the kind of riding the area is really known for among dirt-bikers: true singletrack, motorcycles only, and seasonal.",
    "distanceMiles": 14.2,
    "difficulty": "Difficult",
    "elevationFt": "3,150–6,700 ft",
    "surface": "Long, technical motorcycle singletrack",
    "bestSeason": "May–October (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 19W04 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed — and being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "One of the area's longest moto singletracks",
      "Technical, narrow green-sticker trail",
      "Motorcycle-only — the real reason to come"
    ],
    "trailhead": {
      "name": "Mt Pinos Singletrack (19W04)",
      "lat": 34.7165,
      "lng": -118.9296
    }
  },
  {
    "id": "reyes-peak",
    "name": "Reyes Peak Road",
    "forestRoad": "6N06.1",
    "summary": "Scenic plated ridge road along Pine Mountain.",
    "description": "6N06 runs the Pine Mountain ridge east of Mt Pinos, a high conifer road near 7,500 feet past campgrounds and trailheads with enormous views toward the Sespe and, on clear days, the Channel Islands. Highway-legal-only — a scenic plated cruise; seasonal.",
    "distanceMiles": 5.7,
    "difficulty": "Moderate",
    "elevationFt": "5,100–7,100 ft",
    "surface": "Graded dirt ridge road",
    "bestSeason": "May–October (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6N06.1 is open to highway-legal vehicles only — plated, street-legal bikes only; green-sticker (non-street-legal) bikes are not permitted. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "High conifer ridge along Pine Mountain",
      "Views toward the Sespe wilderness",
      "Scenic plated cruise"
    ],
    "trailhead": {
      "name": "Reyes Peak Road (6N06.1)",
      "lat": 34.6496,
      "lng": -119.3855
    }
  },
  {
    "id": "ballinger-canyon",
    "name": "Ballinger Canyon Road",
    "forestRoad": "9N10.1",
    "summary": "Plated staging road into the Ballinger Canyon OHV area.",
    "description": "9N10 is the graded access road into the Ballinger Canyon OHV area on the Cuyama side, an easy plated ride to the staging area and campground that anchors a big network of OHV trails. The road itself is highway-legal-only; the OHV trail riding branches off it.",
    "distanceMiles": 3.3,
    "difficulty": "Easy",
    "elevationFt": "2,650–3,150 ft",
    "surface": "Wide graded dirt",
    "bestSeason": "Fall–spring (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 9N10.1 is open to highway-legal vehicles only — plated, street-legal bikes only; green-sticker (non-street-legal) bikes are not permitted.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Gateway to the Ballinger Canyon OHV area",
      "Easy plated access road",
      "Anchors a big OHV trail network"
    ],
    "trailhead": {
      "name": "Ballinger Canyon Road (9N10.1)",
      "lat": 34.8868,
      "lng": -119.5005
    }
  }
];
