// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const palmSpringsRoutes: Route[] = [
  {
    "id": "san-jacinto-ridge",
    "name": "San Jacinto Ridge",
    "forestRoad": "5S09",
    "summary": "High, rocky ridge road with sweeping Garner Valley and desert views.",
    "description": "Forest road 5S09 works along the high ridge on the east side of the San Jacintos above Garner Valley — a rough, high-clearance OHV route with loose, rocky, rutted pitches. The reward is a long ridgeline that opens onto the Santa Rosa Mountains and, on clear days, the Coachella Valley far below.",
    "distanceMiles": 11,
    "difficulty": "Difficult",
    "elevationFt": "3,000–6,050 ft",
    "surface": "High-clearance dirt with loose rock and rutted climbs",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5S09 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long ridgeline views over Garner Valley",
      "Genuinely rocky high-clearance OHV riding",
      "Links into the Santa Rosa backcountry network"
    ],
    "trailhead": {
      "name": "San Jacinto Ridge (5S09)",
      "lat": 33.7628,
      "lng": -116.7443
    }
  },
  {
    "id": "red-mountain",
    "name": "Red Mountain OHV Road",
    "forestRoad": "6S22",
    "summary": "Pinyon-slope climb on Red Mountain — green-sticker on part of it.",
    "description": "6S22 climbs through pinyon and chaparral on the flanks of Red Mountain south of Garner Valley, mixing smooth graded stretches with looser, rockier climbs as it gains the ridge. Part of the road is open to all vehicles, so green-sticker access is segment-by-segment — read the signs at each junction.",
    "distanceMiles": 8.1,
    "difficulty": "Moderate",
    "elevationFt": "3,850–4,600 ft",
    "surface": "Graded dirt with rockier, looser climbs up high",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Red Mountain OHV Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only — so access is segment-by-segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Pinyon-and-chaparral high country",
      "Quieter than the Garner Valley fire roads"
    ],
    "trailhead": {
      "name": "Red Mountain OHV Road (6S22)",
      "lat": 33.5871,
      "lng": -116.753
    }
  },
  {
    "id": "indian-canyon",
    "name": "Indian Canyon Road",
    "forestRoad": "4S06",
    "summary": "Canyon road through the Garner Valley high country — partly green-sticker.",
    "description": "4S06 runs up Indian Canyon in the Garner Valley area, a high-clearance road with a mix of forest and high-desert transition, sandy washes, and rocky sections. Part of it is open to all vehicles, so green-sticker access is segment-by-segment — a solid intermediate option that connects to the surrounding road network.",
    "distanceMiles": 7.2,
    "difficulty": "Moderate",
    "elevationFt": "3,150–5,050 ft",
    "surface": "Mixed dirt and sandy wash with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Indian Canyon Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only — so access is segment-by-segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Forest-to-high-desert transition scenery",
      "Connects the Garner Valley road network"
    ],
    "trailhead": {
      "name": "Indian Canyon Road (4S06)",
      "lat": 33.8387,
      "lng": -116.8102
    }
  },
  {
    "id": "indian-mountain",
    "name": "Indian Mountain OHV Road",
    "forestRoad": "4S21",
    "summary": "Short, scenic green-sticker spur toward Indian Mountain.",
    "description": "A shorter designated OHV road (4S21) branching toward Indian Mountain. Open to all vehicles, it's a quick, scenic high-clearance ride with rocky pitches and good views — a nice add-on to a Garner Valley day rather than a destination in itself.",
    "distanceMiles": 4.2,
    "difficulty": "Moderate",
    "elevationFt": "4,700–5,750 ft",
    "surface": "High-clearance dirt with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 4S21 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker designated road",
      "Short, scenic high-clearance spur",
      "Pairs well with the Indian Canyon network"
    ],
    "trailhead": {
      "name": "Indian Mountain OHV Road (4S21)",
      "lat": 33.7973,
      "lng": -116.7777
    }
  },
  {
    "id": "bee-canyon",
    "name": "Bee Canyon OHV Road",
    "forestRoad": "5S07",
    "summary": "Designated OHV road dropping through Bee Canyon.",
    "description": "5S07 follows Bee Canyon as a designated open-to-all-vehicles road. It's a compact green-sticker option with sandy canyon-bottom sections and rockier benches, threading pinyon and scrub on the desert side of the range.",
    "distanceMiles": 4.1,
    "difficulty": "Moderate",
    "elevationFt": "1,950–3,000 ft",
    "surface": "Sandy canyon bottom with rocky benches",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5S07 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker designated road",
      "Sandy canyon-bottom character",
      "Desert-side pinyon and scrub"
    ],
    "trailhead": {
      "name": "Bee Canyon OHV Road (5S07)",
      "lat": 33.7632,
      "lng": -116.823
    }
  },
  {
    "id": "thomas-mountain",
    "name": "Thomas Mountain Road",
    "forestRoad": "6S13",
    "summary": "Long, scenic climb to Thomas Mountain — plated bikes only.",
    "description": "6S13 is a long, graded climb up Thomas Mountain on the west side of Garner Valley, generally smooth enough for passenger cars but a fun, view-packed dual-sport ride. It passes Jeffrey pine, dispersed campsites, and overlooks of Lake Hemet and Garner Valley.",
    "distanceMiles": 15,
    "difficulty": "Moderate",
    "elevationFt": "4,400–6,700 ft",
    "surface": "Long graded dirt, generally smooth",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S13 is open to highway-legal vehicles only — plated, street-legal bikes only; green-sticker (non-street-legal) bikes are not permitted.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Overlooks of Lake Hemet and Garner Valley",
      "Jeffrey pine and dispersed camping",
      "Smooth, beginner-friendly grade (plated only)"
    ],
    "trailhead": {
      "name": "Thomas Mountain Road (6S13)",
      "lat": 33.6577,
      "lng": -116.6653
    }
  },
  {
    "id": "santa-rosa-road",
    "name": "Santa Rosa Mountain Road",
    "forestRoad": "7S02",
    "summary": "Remote high-clearance climb deep into the Santa Rosa Mountains.",
    "description": "7S02 climbs toward the high Santa Rosa Mountains and the Toro Peak area — a remote, high-clearance road with rough, rocky, sometimes washed-out sections. It tops out in cool conifer country with enormous views over the desert; come prepared and plated, since it's highway-legal-only.",
    "distanceMiles": 11.7,
    "difficulty": "Difficult",
    "elevationFt": "4,600–7,950 ft",
    "surface": "Rough, rocky high-clearance road; washouts likely",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 7S02 is open to highway-legal vehicles only — plated, street-legal bikes only; green-sticker (non-street-legal) bikes are not permitted.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Remote, high Santa Rosa Mountains",
      "Huge desert overlooks near Toro Peak",
      "Cool conifer country up high (plated only)"
    ],
    "trailhead": {
      "name": "Santa Rosa Mountain Road (7S02)",
      "lat": 33.5679,
      "lng": -116.5118
    }
  },
  {
    "id": "black-mountain-road",
    "name": "Black Mountain Road",
    "forestRoad": "4S01",
    "summary": "Forest climb toward the Black Mountain lookout and trails.",
    "description": "4S01 climbs the Black Mountain area on the north side of the San Jacintos through pine forest toward the historic lookout and trailheads. A scenic, moderate graded road — highway-legal-only, so it's a plated dual-sport ride rather than a green-sticker one.",
    "distanceMiles": 11.4,
    "difficulty": "Moderate",
    "elevationFt": "5,350–7,700 ft",
    "surface": "Graded dirt with rocky, rutted sections",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 4S01 is open to highway-legal vehicles only — plated, street-legal bikes only; green-sticker (non-street-legal) bikes are not permitted.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Pine forest toward Black Mountain lookout",
      "Cooler high-elevation riding",
      "Scenic moderate grade (plated only)"
    ],
    "trailhead": {
      "name": "Black Mountain Road (4S01)",
      "lat": 33.7967,
      "lng": -116.7578
    }
  }
];
