// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const palomarRoutes: Route[] = [
  {
    "id": "palomar-divide",
    "name": "Palomar Divide Road",
    "forestRoad": "9S07",
    "summary": "The long backbone ridge of Palomar Mountain, about 13 miles.",
    "description": "9S07 runs the Palomar Divide the length of the mountain, roughly 13 miles of graded-to-rocky ridge road through oak and conifer with sweeping views over the San Diego backcountry and out to the desert. The signature ride on Palomar: a long, scenic plated dual-sport cruise, smoother than the Santa Ana divide but just as big on views. Open to street-legal vehicles only.",
    "distanceMiles": 13.1,
    "difficulty": "Moderate",
    "elevationFt": "3,050–6,000 ft",
    "surface": "Graded-to-rocky ridge road",
    "bestSeason": "Spring and fall (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 9S07 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "About 13 miles along the Palomar crest",
      "Big San Diego backcountry and desert views",
      "The signature ride on the mountain"
    ],
    "trailhead": {
      "name": "Palomar Divide Road (9S07)",
      "lat": 33.3309,
      "lng": -116.7091
    }
  },
  {
    "id": "high-point",
    "name": "High Point Road",
    "forestRoad": "8S05",
    "summary": "High-clearance climb on the northeast flank of Palomar Mountain.",
    "description": "8S05 climbs the northeast flank of Palomar above the Aguanga and Lake Henshaw side, gaining a couple of thousand feet of forest through conifer and oak. A high-clearance road with rocky sections and a steadier, more remote feel than the divide. It tops out around 4,900 feet, below the High Point lookout itself, which sits on a separate gated road. Open to street-legal vehicles only.",
    "distanceMiles": 9.4,
    "difficulty": "Moderate",
    "elevationFt": "2,000–4,900 ft",
    "surface": "High-clearance dirt with rocky sections",
    "bestSeason": "Spring and fall (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 8S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Forested climb on the northeast flank",
      "Quieter, remote-feeling high-clearance road",
      "Tops out around 4,900 feet"
    ],
    "trailhead": {
      "name": "High Point Road (8S05)",
      "lat": 33.4403,
      "lng": -116.857
    }
  },
  {
    "id": "indian-flats",
    "name": "Indian Flats Road",
    "forestRoad": "9S05",
    "summary": "Backcountry road into the Indian Flats country on the north side.",
    "description": "9S05 drops into the Indian Flats country on the north side of Palomar near Lake Henshaw, a graded-to-rocky backcountry road through chaparral and oak toward the Indian Flats campground. A quieter plated ride than the divide, with a more remote feel and good seat time. Open to street-legal vehicles only.",
    "distanceMiles": 10.7,
    "difficulty": "Moderate",
    "elevationFt": "2,900–4,350 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "Spring and fall (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 9S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Into the remote Indian Flats country",
      "Toward the Indian Flats campground",
      "Quieter companion to the Divide"
    ],
    "trailhead": {
      "name": "Indian Flats Road (9S05)",
      "lat": 33.2863,
      "lng": -116.6603
    }
  },
  {
    "id": "oak-grove-road",
    "name": "Oak Grove Road",
    "forestRoad": "9S09",
    "summary": "Short access road linking Highway 79 to the Palomar Divide.",
    "description": "9S09 is the short access road off Highway 79 at Oak Grove that ties into the Palomar Divide, an easy graded climb through oak and chaparral. Brief on its own, but it's the natural way onto the ridge from the east, so it earns its place as the connector that starts a divide day. Open to street-legal vehicles only.",
    "distanceMiles": 1.8,
    "difficulty": "Easy",
    "elevationFt": "4,900–5,650 ft",
    "surface": "Short graded climb, generally smooth",
    "bestSeason": "Spring and fall (hot in summer, muddy after storms)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 9S09 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Eastern access onto the Palomar Divide",
      "Easy oak-and-chaparral grade",
      "The natural start of a divide day"
    ],
    "trailhead": {
      "name": "Oak Grove Road (9S09)",
      "lat": 33.3762,
      "lng": -116.827
    }
  }
];
