// AUTO-GENERATED by scripts/build-angeles-routes.mjs — do not edit by hand.
// Geometry: USFS TrailNFS (trails) and RoadBasic (roads) inventories, EDW.
// Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const rowherFlatsRoutes: Route[] = [
  {
    "id": "rowher-4x4",
    "name": "Rowher 4x4 Trail",
    "summary": "The marquee trail of the system: five miles of steep, loose climbing out of the staging flats.",
    "description": "The Rowher 4x4 Trail is the longest trail in the system and the one the area is named for, five miles of steep, loose climbing from the staging flats up toward the Sierra Pelona high country. It carries a special designation on the motor vehicle use map and is managed for 4x4s and OHVs together, so expect ruts, ledges, and company on weekends. The payoff is real elevation gain and long views over the Santa Clarita valley.",
    "distanceMiles": 5,
    "difficulty": "Difficult",
    "elevationFt": "2,700–4,850 ft",
    "surface": "Steep, loose 4x4 trail, rutted with rocky pitches",
    "bestSeason": "October–May (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the Forest Service trail inventory, this trail carries a special designation on the motor vehicle use map, and green-sticker (non-street-legal) OHVs are allowed. Check the posted MVUM at the staging area for the specifics. Registration + spark arrestor required, and an Adventure Pass covers parking.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "Longest trail in the Rowher system",
      "Climbs toward the Sierra Pelona high country",
      "Big views over the Santa Clarita valley"
    ],
    "trailhead": {
      "name": "Rowher 4x4 Trail",
      "lat": 34.5316,
      "lng": -118.3666
    }
  },
  {
    "id": "rowher-singletrack",
    "name": "Rowher Singletrack (Silverking, Yucca & King Snake)",
    "summary": "The closest designated motorcycle singletrack to Los Angeles: three trails of narrow, technical tread.",
    "description": "Silverking, Yucca, and King Snake are the singletrack heart of Rowher Flats: narrow motorcycle-only tread threading the slopes above the staging areas. It's only about three miles all told, but it's genuine singletrack, tight, loose, and technical, and it's the closest designated singletrack to Los Angeles proper. Ride it as laps rather than a point-to-point.",
    "distanceMiles": 3.1,
    "difficulty": "Difficult",
    "elevationFt": "2,150–4,400 ft",
    "surface": "Narrow motorcycle-only singletrack, loose and technical",
    "bestSeason": "October–May (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the Forest Service trail inventory, this is designated for motorcycles only, so green-sticker (non-street-legal) bikes are allowed and nothing wider is. It's true singletrack. Registration + spark arrestor required, and parking at the staging areas takes an Adventure Pass.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "True motorcycle-only singletrack",
      "The closest designated singletrack to LA",
      "Tight, technical tread worth lapping"
    ],
    "trailhead": {
      "name": "Rowher Singletrack (Silverking, Yucca & King Snake)",
      "lat": 34.5164,
      "lng": -118.4061
    }
  },
  {
    "id": "rowher-buffer-loop",
    "name": "Buffer, Spring & Stage",
    "summary": "The natural first lap: three linked trails through the heart of the trail system.",
    "description": "Buffer is the longest of the trails open to vehicles 50 inches or less, three miles working the drainages at the core of the system, and with Spring and Stage it links into a natural circuit. The tread is classic Rowher: loose soil over hardpack, whooped out in the flats, with short punchy climbs between drainages. A good first lap to learn the area before committing to the 4x4 trail or the singletrack.",
    "distanceMiles": 5.3,
    "difficulty": "Moderate",
    "elevationFt": "2,450–2,900 ft",
    "surface": "Loose soil over hardpack, whooped in the flats",
    "bestSeason": "October–May (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the Forest Service trail inventory, Buffer, Spring & Stage is designated for vehicles 50 inches or less, so green-sticker (non-street-legal) bikes and quads are allowed. Registration + spark arrestor required, and parking at the Rowher staging areas takes an Adventure Pass.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "A natural circuit through the core of the system",
      "Open to green-sticker bikes and quads alike",
      "The right warm-up before the harder trails"
    ],
    "trailhead": {
      "name": "Buffer, Spring & Stage",
      "lat": 34.5309,
      "lng": -118.3676
    }
  },
  {
    "id": "rowher-broken-spoke",
    "name": "Broken Spoke, Sidewinder & Sierra",
    "summary": "The twistier side of the network, a step up from the Buffer circuit.",
    "description": "Broken Spoke runs nearly three miles on the quieter side of the system, and Sidewinder and Sierra hang off it for another three and a half. The names are honest: this side twists harder and climbs steeper than the Buffer circuit, with off-camber corners and loose, marbly tread that keeps bikes and quads honest. String all three together for a solid green-sticker outing away from the staging crowds.",
    "distanceMiles": 6.4,
    "difficulty": "Moderate",
    "elevationFt": "2,350–4,700 ft",
    "surface": "Twisting two-track, loose and off camber in spots",
    "bestSeason": "October–May (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the Forest Service trail inventory, Broken Spoke, Sidewinder & Sierra is designated for vehicles 50 inches or less, so green-sticker (non-street-legal) bikes and quads are allowed. Registration + spark arrestor required, and parking at the Rowher staging areas takes an Adventure Pass.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "Twistier and steeper than the Buffer side",
      "Three trails string into one outing",
      "The quieter corner of the network"
    ],
    "trailhead": {
      "name": "Broken Spoke, Sidewinder & Sierra",
      "lat": 34.5215,
      "lng": -118.394
    }
  },
  {
    "id": "santa-clara-divide",
    "name": "Santa Clara Divide Road",
    "forestRoad": "3N17",
    "summary": "The plated epic: 46 miles along the divide past Mt. Gleason to Mill Creek Summit.",
    "description": "Santa Clara Divide Road runs the long ridge between the Santa Clarita valley and the high Angeles backcountry, from Sand Canyon up past Mt. Gleason and down to Mill Creek Summit, with more segments carrying east toward Mt. Pacifico. Stretches are paved, long stretches are dirt not maintained for passenger cars, and the whole thing strings into one of the biggest dual-sport days this close to LA. Bring a plated bike, fuel for the full distance, and expect the odd locked gate in fire season.",
    "distanceMiles": 46.1,
    "difficulty": "Moderate",
    "elevationFt": "2,750–6,400 ft",
    "surface": "Mixed pavement and dirt, rough in the unmaintained stretches",
    "bestSeason": "April–November (snow and storm gates possible in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "unconfirmed",
      "note": "The Angeles publishes its motor vehicle use map only as a printed map, so green-sticker access on this road could not be verified against an authoritative source. Treat it as open to street-legal (plated) vehicles only unless the published MVUM says otherwise.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "One of the biggest dual-sport days near LA",
      "Tops out near Mt. Gleason around 6,000 feet",
      "Mixes pavement with remote dirt"
    ],
    "trailhead": {
      "name": "Bear Divide (Sand Canyon)",
      "lat": 34.3591,
      "lng": -118.4534
    }
  },
  {
    "id": "sierra-pelona-road",
    "name": "Sierra Pelona Road",
    "forestRoad": "6N07",
    "summary": "Nine miles of ridge dirt along the Sierra Pelona crest, directly above the OHV area.",
    "description": "Sierra Pelona Road climbs to the ridgeline above Rowher Flats and runs the crest for nine miles, chaparral and grassy balds with the OHV area below on one side and the Antelope Valley out the other. It's graded dirt not maintained for passenger cars, easy going on a plated dual-sport and the natural extension after a morning on the trails below. The trail system and the road are separate networks, so plan on street-legal access up here.",
    "distanceMiles": 9.3,
    "difficulty": "Easy",
    "elevationFt": "2,000–4,800 ft",
    "surface": "Graded ridge dirt, rough in spots",
    "bestSeason": "October–June (exposed and hot midsummer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "unconfirmed",
      "note": "The Angeles publishes its motor vehicle use map only as a printed map, so green-sticker access on this road could not be verified against an authoritative source. Treat it as open to street-legal (plated) vehicles only unless the published MVUM says otherwise.",
      "source": "USFS trail and road inventories (EDW), 2026"
    },
    "highlights": [
      "Crest views over the OHV area and the Antelope Valley",
      "Easy plated dual-sport dirt",
      "Pairs with a morning on the Rowher trails"
    ],
    "trailhead": {
      "name": "Sierra Pelona Road",
      "lat": 34.5265,
      "lng": -118.4424
    }
  }
];
