// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const sanLuisObispoRoutes: Route[] = [
  {
    "id": "hi-mountain",
    "name": "Hi Mountain OHV Road",
    "forestRoad": "30S11",
    "summary": "Climb to the Hi Mountain lookout in the heart of the Pozo OHV area.",
    "description": "30S11 is the signature green-sticker road of the Pozo / La Panza OHV area, climbing rocky, high-clearance tread through chaparral and oak toward Hi Mountain and its historic condor lookout. Big Santa Lucia Range views and a genuine OHV-designated route, open seasonally, and a long way from anywhere.",
    "distanceMiles": 8.2,
    "difficulty": "Difficult",
    "elevationFt": "1,950–3,050 ft",
    "surface": "Rocky, high-clearance OHV-area dirt",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 30S11 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Heart of the Pozo OHV area",
      "Climbs toward the Hi Mountain condor lookout",
      "Designated green-sticker road"
    ],
    "trailhead": {
      "name": "Hi Mountain OHV Road (30S11)",
      "lat": 35.2662,
      "lng": -120.4078
    }
  },
  {
    "id": "pozo-singletrack",
    "name": "Pozo OHV Singletrack",
    "forestRoad": "16E21",
    "summary": "The longest designated OHV trail in the Pozo singletrack network.",
    "description": "Trail 16E21 is the longest dedicated OHV trail in the Pozo / La Panza area, narrow green-sticker singletrack threading the chaparral and oak well off the OHV roads. The Pozo trail network is the real draw for dirt-bikers here, and this is its centerpiece: technical, remote, and seasonal (closed when wet).",
    "distanceMiles": 9.1,
    "difficulty": "Difficult",
    "elevationFt": "1,800–2,750 ft",
    "surface": "Narrow OHV singletrack through chaparral",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, trail 16E21 is a designated OHV trail open to motorcycles, so green-sticker (non-street-legal) bikes are allowed. Being narrow-gauge singletrack, it's a true OHV trail, not a road. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Longest trail in the Pozo singletrack network",
      "Narrow, technical green-sticker riding",
      "The real draw of the Pozo OHV area"
    ],
    "trailhead": {
      "name": "Pozo OHV Singletrack (16E21)",
      "lat": 35.3592,
      "lng": -120.2757
    }
  },
  {
    "id": "rock-front",
    "name": "Rock Front OHV Road",
    "forestRoad": "30S06.1",
    "summary": "Designated green-sticker OHV road through the La Panza chaparral.",
    "description": "30S06 is an open-to-all-vehicles OHV road in the La Panza country, mixing rocky benches and sandy stretches through dense chaparral. A solid intermediate green-sticker ride that links into the surrounding Pozo OHV network, seasonal when wet.",
    "distanceMiles": 4,
    "difficulty": "Moderate",
    "elevationFt": "1,250–1,900 ft",
    "surface": "Rocky and sandy OHV-area tread",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 30S06.1 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated green-sticker (open to all vehicles)",
      "La Panza chaparral country",
      "Connects the Pozo OHV network"
    ],
    "trailhead": {
      "name": "Rock Front OHV Road (30S06.1)",
      "lat": 35.1108,
      "lng": -120.0957
    }
  },
  {
    "id": "queen-bee-loop",
    "name": "Queen Bee Loop OHV",
    "forestRoad": "29S18.1, 29S18.2",
    "summary": "Short green-sticker loop in the Pozo OHV area.",
    "description": "The Queen Bee Loop (29S18) is a compact designated OHV road in the Pozo area, open to all vehicles, with sandy and rocky tread through oak and chaparral. A fun, low-commitment green-sticker loop to add onto a bigger day, open seasonally.",
    "distanceMiles": 4.6,
    "difficulty": "Moderate",
    "elevationFt": "1,750–2,600 ft",
    "surface": "Sandy and rocky OHV-area tread",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 29S18.1 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated green-sticker loop",
      "Oak-and-chaparral Pozo country",
      "Good add-on to the Hi Mountain ride"
    ],
    "trailhead": {
      "name": "Queen Bee Loop OHV (29S18.1)",
      "lat": 35.3552,
      "lng": -120.2518
    }
  },
  {
    "id": "old-sierra",
    "name": "Old Sierra OHV Road",
    "forestRoad": "12N03.1",
    "summary": "Short, rocky green-sticker spur toward the Sierra Madre country.",
    "description": "12N03 (Old Sierra) is a short open-to-all-vehicles OHV road on the approach to the Sierra Madre high country, rocky, high-clearance tread with chaparral and grassland views. A brief green-sticker option best paired with the longer roads nearby; seasonal.",
    "distanceMiles": 2,
    "difficulty": "Moderate",
    "elevationFt": "2,600–3,050 ft",
    "surface": "Rocky high-clearance OHV-area dirt",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 12N03.1 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Designated green-sticker road",
      "Sierra Madre approach country",
      "Pairs with Sierra Madre Road"
    ],
    "trailhead": {
      "name": "Old Sierra OHV Road (12N03.1)",
      "lat": 35.0715,
      "lng": -120.0574
    }
  },
  {
    "id": "navajo-road",
    "name": "Navajo Road",
    "forestRoad": "29S02.1, 29S02.2",
    "summary": "Backcountry road into the Pozo OHV area, green-sticker on part of it.",
    "description": "Navajo Road (29S02) drops into the Pozo / La Panza backcountry, mixing graded stretches with rockier sections through oak woodland. Part of it is designated open to all vehicles and part is highway-legal-only, so green-sticker access is segment-by-segment; read the signs at each junction. Seasonal closures apply.",
    "distanceMiles": 7.8,
    "difficulty": "Moderate",
    "elevationFt": "1,750–2,650 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "Fall–spring (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Navajo Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are highway-legal-only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Oak-woodland Pozo backcountry",
      "Gateway to the OHV network"
    ],
    "trailhead": {
      "name": "Navajo Road (29S02.1)",
      "lat": 35.3443,
      "lng": -120.3549
    }
  },
  {
    "id": "sierra-madre-road",
    "name": "Sierra Madre Road",
    "forestRoad": "32S13.1",
    "summary": "The ~28-mile Sierra Madre Ridge, remote plated backcountry.",
    "description": "Sierra Madre Road (32S13) runs the long, remote Sierra Madre Ridge, one of the great backcountry roads in Los Padres, roughly 28 miles of graded-to-rocky ridgeline through grassland and chaparral with enormous, lonely views. Highway-legal-only, so it's a plated adventure-bike ride; gated and seasonal, and genuinely committing, carry everything.",
    "distanceMiles": 28.6,
    "difficulty": "Difficult",
    "elevationFt": "1,300–5,600 ft",
    "surface": "Long, remote graded-to-rocky ridge road",
    "bestSeason": "Spring–fall (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 32S13.1 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "~28 miles of remote Sierra Madre Ridge",
      "Huge, lonely grassland-and-chaparral views",
      "Classic plated backcountry adventure"
    ],
    "trailhead": {
      "name": "Sierra Madre Road (32S13.1)",
      "lat": 35.1117,
      "lng": -120.0915
    }
  },
  {
    "id": "fernandez-road",
    "name": "Fernandez Road",
    "forestRoad": "28S02.1, 28S02.2",
    "summary": "Quiet plated forest road in the Santa Lucia backcountry.",
    "description": "Fernandez Road (28S02) is a quieter highway-legal-only road through the Santa Lucia backcountry near Pozo, with graded dirt and rocky sections through oak and chaparral. A relaxed plated ride and a way to link the area without the technical or seasonal demands of the OHV roads.",
    "distanceMiles": 6.6,
    "difficulty": "Moderate",
    "elevationFt": "1,700–1,950 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 28S02.1 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Quiet Santa Lucia backcountry",
      "Oak-and-chaparral scenery",
      "Relaxed plated ride"
    ],
    "trailhead": {
      "name": "Fernandez Road (28S02.1)",
      "lat": 35.429,
      "lng": -120.3444
    }
  },
];
