// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const sanJacintoRoutes: Route[] = [
  {
    "id": "san-jacinto-ridge",
    "name": "San Jacinto Ridge",
    "forestRoad": "5S09",
    "summary": "High, rocky ridge road with sweeping Garner Valley and desert views.",
    "description": "Forest road 5S09 works along the high ridge on the east side of the San Jacintos above Garner Valley, a rough, high-clearance OHV route with loose, rocky, rutted pitches. Up top, a long ridgeline opens onto the Santa Rosa Mountains and, on clear days, the Coachella Valley far below.",
    "distanceMiles": 11,
    "difficulty": "Difficult",
    "elevationFt": "3,000–6,050 ft",
    "surface": "High-clearance dirt with loose rock and rutted climbs",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5S09 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long ridgeline views over Garner Valley",
      "Genuinely rocky high-clearance OHV riding",
      "Links into the Santa Rosa backcountry network"
    ],
    "trailhead": {
      "name": "San Jacinto Ridge (5S09)",
      "lat": 33.7628,
      "lng": -116.7443
    }
  },
  {
    "id": "red-mountain",
    "name": "Red Mountain OHV Road",
    "forestRoad": "6S22",
    "summary": "Pinyon-slope climb on Red Mountain, green-sticker on part of it.",
    "description": "6S22 climbs through pinyon and chaparral on the flanks of Red Mountain south of Garner Valley, mixing smooth graded stretches with looser, rockier climbs as it gains the ridge. Part of the road is open to all vehicles, so green-sticker access is segment-by-segment; read the signs at each junction.",
    "distanceMiles": 8.1,
    "difficulty": "Moderate",
    "elevationFt": "3,850–4,600 ft",
    "surface": "Graded dirt with rockier, looser climbs up high",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Red Mountain OHV Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Pinyon-and-chaparral high country",
      "Quieter than the Garner Valley fire roads"
    ],
    "trailhead": {
      "name": "Red Mountain OHV Road (6S22)",
      "lat": 33.5871,
      "lng": -116.753
    }
  },
  {
    "id": "indian-canyon",
    "name": "Indian Canyon Road",
    "forestRoad": "4S06",
    "summary": "Canyon road through the Garner Valley high country, partly green-sticker.",
    "description": "4S06 runs up Indian Canyon in the Garner Valley area, a high-clearance road with a mix of forest and high-desert transition, sandy washes, and rocky sections. Part of it is open to all vehicles, so green-sticker access is segment-by-segment, a solid intermediate option that connects to the surrounding road network.",
    "distanceMiles": 7.2,
    "difficulty": "Moderate",
    "elevationFt": "3,150–5,050 ft",
    "surface": "Mixed dirt and sandy wash with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Indian Canyon Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road",
      "Forest-to-high-desert transition scenery",
      "Connects the Garner Valley road network"
    ],
    "trailhead": {
      "name": "Indian Canyon Road (4S06)",
      "lat": 33.8387,
      "lng": -116.8102
    }
  },
  {
    "id": "indian-mountain",
    "name": "Indian Mountain OHV Road",
    "forestRoad": "4S21",
    "summary": "Short, scenic green-sticker spur toward Indian Mountain.",
    "description": "A shorter designated OHV road (4S21) branching toward Indian Mountain. Open to all vehicles, it's a quick, scenic high-clearance ride with rocky pitches and good views, a nice add-on to a Garner Valley day rather than a destination in itself.",
    "distanceMiles": 4.2,
    "difficulty": "Moderate",
    "elevationFt": "4,700–5,750 ft",
    "surface": "High-clearance dirt with rocky sections",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 4S21 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker designated road",
      "Short, scenic high-clearance spur",
      "Pairs well with the Indian Canyon network"
    ],
    "trailhead": {
      "name": "Indian Mountain OHV Road (4S21)",
      "lat": 33.7973,
      "lng": -116.7777
    }
  },
  {
    "id": "bee-canyon",
    "name": "Bee Canyon OHV Road",
    "forestRoad": "5S07",
    "summary": "Designated OHV road dropping through Bee Canyon.",
    "description": "5S07 follows Bee Canyon as a designated road open to all vehicles. It's a compact green-sticker option with sandy canyon-bottom sections and rockier benches, threading pinyon and scrub on the desert side of the range.",
    "distanceMiles": 4.1,
    "difficulty": "Moderate",
    "elevationFt": "1,950–3,000 ft",
    "surface": "Sandy canyon bottom with rocky benches",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5S07 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker designated road",
      "Sandy canyon-bottom character",
      "Desert-side pinyon and scrub"
    ],
    "trailhead": {
      "name": "Bee Canyon OHV Road (5S07)",
      "lat": 33.7632,
      "lng": -116.823
    }
  },
  {
    "id": "thomas-mountain",
    "name": "Thomas Mountain Road",
    "forestRoad": "6S13",
    "summary": "Long, scenic climb to Thomas Mountain, plated bikes only.",
    "description": "6S13 is a long, graded climb up Thomas Mountain on the west side of Garner Valley, generally smooth enough for passenger cars but a fun, view-packed dual-sport ride. It passes Jeffrey pine, dispersed campsites, and overlooks of Lake Hemet and Garner Valley.",
    "distanceMiles": 15,
    "difficulty": "Moderate",
    "elevationFt": "4,400–6,700 ft",
    "surface": "Long graded dirt, generally smooth",
    "bestSeason": "April–November",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S13 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Overlooks of Lake Hemet and Garner Valley",
      "Jeffrey pine and dispersed camping",
      "Smooth, beginner-friendly grade (plated only)"
    ],
    "trailhead": {
      "name": "Thomas Mountain Road (6S13)",
      "lat": 33.6577,
      "lng": -116.6653
    }
  },
  {
    "id": "santa-rosa-road",
    "name": "Santa Rosa Mountain Road",
    "forestRoad": "7S02",
    "summary": "Remote high-clearance climb deep into the Santa Rosa Mountains.",
    "description": "7S02 climbs toward the high Santa Rosa Mountains and the Toro Peak area, a remote, high-clearance road with rough, rocky, sometimes washed-out sections. It tops out in cool conifer country with enormous views over the desert; come prepared and plated, since it's open to street-legal vehicles only.",
    "distanceMiles": 11.7,
    "difficulty": "Difficult",
    "elevationFt": "4,600–7,950 ft",
    "surface": "Rough, rocky high-clearance road; washouts likely",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 7S02 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Remote, high Santa Rosa Mountains",
      "Huge desert overlooks near Toro Peak",
      "Cool conifer country up high (plated only)"
    ],
    "trailhead": {
      "name": "Santa Rosa Mountain Road (7S02)",
      "lat": 33.5679,
      "lng": -116.5118
    }
  },
  {
    "id": "black-mountain-road",
    "name": "Black Mountain Road",
    "forestRoad": "4S01",
    "summary": "Long forest climb to the Black Mountain lookout above Idyllwild.",
    "description": "4S01 climbs the north flank of Black Mountain through dense pine and cedar above Idyllwild toward the historic fire lookout and the Black Mountain trailheads. A scenic, sustained graded climb with rocky, rutted sections. Highway-legal-only, so it's a plated dual-sport ride.",
    "distanceMiles": 11.4,
    "difficulty": "Difficult",
    "elevationFt": "5,350–7,700 ft",
    "surface": "Graded dirt with rocky, rutted climbs",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 4S01 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Climbs to the Black Mountain fire lookout",
      "Dense pine-and-cedar San Jacinto forest",
      "Cooler high-elevation riding (plated only)"
    ],
    "trailhead": {
      "name": "Black Mountain Road (4S01)",
      "lat": 33.7967,
      "lng": -116.7578
    }
  },
  {
    "id": "idyllwild-control-road",
    "name": "Idyllwild Control Road",
    "forestRoad": "5S06",
    "summary": "Classic dirt connector linking Idyllwild to the high country.",
    "description": "5S06 is a graded forest road threading the pines near Idyllwild, a relaxed plated dual-sport ride with good sight lines and forest scenery. Highway-legal-only, it's a pleasant way to link the area's roads and trailheads without technical demands.",
    "distanceMiles": 6.1,
    "difficulty": "Moderate",
    "elevationFt": "2,350–5,100 ft",
    "surface": "Graded dirt, generally smooth",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 5S06 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Easy pine-forest cruising near town",
      "Links the Idyllwild road network",
      "Beginner-friendly grade (plated only)"
    ],
    "trailhead": {
      "name": "Idyllwild Control Road (5S06)",
      "lat": 33.7339,
      "lng": -116.7507
    }
  },
  {
    "id": "dark-canyon-road",
    "name": "Dark Canyon Road",
    "forestRoad": "4S02",
    "summary": "Short forest road into the Dark Canyon drainage.",
    "description": "4S02 drops into the Dark Canyon area northwest of Idyllwild, a shaded forest road serving the campground and trailheads along the San Jacinto's western canyons. A short, scenic plated ride through pine and oak, highway-legal vehicles only.",
    "distanceMiles": 5.6,
    "difficulty": "Moderate",
    "elevationFt": "5,750–6,300 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 4S02 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Shaded Dark Canyon forest",
      "Campground and trailhead access",
      "Short, scenic plated ride"
    ],
    "trailhead": {
      "name": "Dark Canyon Road (4S02)",
      "lat": 33.8099,
      "lng": -116.7492
    }
  },
  {
    "id": "fobes-ranch-road",
    "name": "Fobes Ranch Road",
    "forestRoad": "6S05",
    "summary": "Plated spur to the Fobes Ranch PCT trailhead.",
    "description": "6S05 climbs to the Fobes Ranch trailhead on the south side of the San Jacintos, a popular jumping-off point for the Pacific Crest Trail. A moderate, rocky graded road with chaparral-to-forest transition and big views, plated dual-sport, highway-legal only.",
    "distanceMiles": 4,
    "difficulty": "Moderate",
    "elevationFt": "4,450–5,250 ft",
    "surface": "Rocky graded dirt; rougher up high",
    "bestSeason": "May–October",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Access to the Fobes Ranch PCT trailhead",
      "Chaparral-to-forest transition",
      "Big San Jacinto views (plated only)"
    ],
    "trailhead": {
      "name": "Fobes Ranch Road (6S05)",
      "lat": 33.6375,
      "lng": -116.6457
    }
  }
];
