// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const sanGorgonioRoutes: Route[] = [
  {
    "id": "coon-creek-jumpoff",
    "name": "Coon Creek Jumpoff Road",
    "forestRoad": "1N02",
    "summary": "Rough high-clearance road to the Coon Creek Jumpoff overlook.",
    "description": "1N02 climbs and traverses to the Coon Creek Jumpoff, a dramatic overlook where the forest drops away toward the desert below San Gorgonio. The road is genuinely rough in stretches, rocky, eroded, high-clearance dual-sport riding, with one of the bigger view payoffs in the area. Open to street-legal vehicles only, so plated bikes only.",
    "distanceMiles": 7.7,
    "difficulty": "Difficult",
    "elevationFt": "6,900–8,500 ft",
    "surface": "Rough, rocky, eroded high-clearance dirt",
    "bestSeason": "May–November (snow up high in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 1N02 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Overlook where the forest drops to the desert",
      "Genuinely rough high-clearance riding",
      "One of the best view payoffs in the area"
    ],
    "trailhead": {
      "name": "Coon Creek Jumpoff Road (1N02)",
      "lat": 34.1622,
      "lng": -116.7858
    }
  },
  {
    "id": "radford-front-line",
    "name": "Radford Front Line Road",
    "forestRoad": "1N04",
    "summary": "Long front-line road through the Barton Flats high country.",
    "description": "1N04 runs the front line through the Barton Flats and Santa Ana River high country, a long graded-to-rocky road serving the camps, trailheads, and overlooks along the south side of the range. A scenic plated dual-sport ride with steady mileage and pine-forest views toward San Gorgonio. Open to street-legal vehicles only.",
    "distanceMiles": 10.5,
    "difficulty": "Moderate",
    "elevationFt": "5,050–6,350 ft",
    "surface": "Graded dirt with rockier sections",
    "bestSeason": "May–November (snow up high in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 1N04 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long ride through the Barton Flats country",
      "Camps, trailheads, and overlooks",
      "Pine-forest views toward San Gorgonio"
    ],
    "trailhead": {
      "name": "Radford Front Line Road (1N04)",
      "lat": 34.1706,
      "lng": -116.8262
    }
  },
  {
    "id": "wildhorse-meadow",
    "name": "Wildhorse Meadow Road",
    "forestRoad": "2N93",
    "summary": "Long high-clearance climb to Wildhorse Meadow, about 11 miles.",
    "description": "2N93 runs about 11 miles up toward Wildhorse Meadow on the slopes above the Santa Ana River, a high-clearance road mixing rocky climbs with forest and meadow as it gains real elevation toward the crest. A quieter plated ride with cool conifer country and meadows near the top. Open to street-legal vehicles only.",
    "distanceMiles": 11.6,
    "difficulty": "Moderate",
    "elevationFt": "7,050–8,750 ft",
    "surface": "Rocky, high-clearance climb",
    "bestSeason": "May–November (snow up high in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 2N93 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Climbs to Wildhorse Meadow",
      "Forest-and-meadow high country",
      "Quieter than the front-line roads"
    ],
    "trailhead": {
      "name": "Wildhorse Meadow Road (2N93)",
      "lat": 34.1742,
      "lng": -116.7534
    }
  },
  {
    "id": "fish-creek-meadows",
    "name": "Fish Creek Meadows Road",
    "forestRoad": "1N05",
    "summary": "Forest road into the Fish Creek and Heart Bar meadows.",
    "description": "1N05 runs into the Fish Creek and Heart Bar Meadows country on the east end of the area, graded forest road through pine and meadow toward the Fish Creek trailheads near the San Gorgonio Wilderness boundary. A relaxed, scenic plated ride; the wilderness itself is closed to motors, so the trailheads are places to park, not ride. Open to street-legal vehicles only.",
    "distanceMiles": 6.5,
    "difficulty": "Moderate",
    "elevationFt": "7,000–8,350 ft",
    "surface": "Graded dirt with rocky sections",
    "bestSeason": "May–November (snow up high in winter)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 1N05 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Into the Fish Creek and Heart Bar meadows",
      "Pine-and-meadow forest scenery",
      "Trailheads near the San Gorgonio Wilderness"
    ],
    "trailhead": {
      "name": "Fish Creek Meadows Road (1N05)",
      "lat": 34.151,
      "lng": -116.772
    }
  },
  {
    "id": "city-creek",
    "name": "City Creek Road",
    "forestRoad": "1N09",
    "summary": "Long graded traverse along the front of the range, about 22 miles.",
    "description": "1N09 is the long one here: roughly 22 miles of graded road traversing the front of the range above the City Creek drainage, the kind of ride you do to cover ground rather than for any single feature. The grade is gentle but the distance is real, winding through chaparral and oak with views out over the San Bernardino Valley. Open to street-legal vehicles only.",
    "distanceMiles": 22.4,
    "difficulty": "Moderate",
    "elevationFt": "2,950–4,900 ft",
    "surface": "Long graded dirt, gentle grade",
    "bestSeason": "Year-round (hot in summer)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 1N09 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "About 22 miles along the range front",
      "Views over the San Bernardino Valley",
      "Distance ride, not a technical one"
    ],
    "trailhead": {
      "name": "City Creek Road (1N09)",
      "lat": 34.1771,
      "lng": -117.1539
    }
  }
];
