// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const santaAnaRoutes: Route[] = [
  {
    "id": "north-main-divide",
    "name": "North Main Divide Road",
    "forestRoad": "3S04",
    "summary": "The legendary ~35-mile crest of the Santa Ana Mountains over Saddleback.",
    "description": "The North Main Divide Truck Trail (3S04) runs the spine of the Santa Ana Mountains past Santiago and Modjeska Peaks (Saddleback), a long, exposed ridge road with rocky, rutted high-clearance sections and enormous views from the Inland Empire to the Pacific. A classic SoCal plated dual-sport / adventure ride, highway-legal only, and a serious day of riding.",
    "distanceMiles": 34.7,
    "difficulty": "Difficult",
    "elevationFt": "2,650–5,550 ft",
    "surface": "Long, rocky high-clearance ridge road",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 3S04 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Rides the crest past Santiago Peak (Saddleback)",
      "Inland-Empire-to-Pacific views",
      "Marquee plated adventure ride near LA/OC"
    ],
    "trailhead": {
      "name": "North Main Divide Road (3S04)",
      "lat": 33.8211,
      "lng": -117.6391
    }
  },
  {
    "id": "south-main-divide",
    "name": "South Main Divide Road",
    "forestRoad": "6S07",
    "summary": "The southern half of the divide toward El Cariso and Lake Elsinore.",
    "description": "South Main Divide (6S07) continues the ridge south from the Ortega Highway toward El Cariso and the Lake Elsinore side, generally smoother than the north divide with chaparral ridgetops and overlooks of the lake and valley. A scenic, moderate plated ride, highway-legal only.",
    "distanceMiles": 16.2,
    "difficulty": "Moderate",
    "elevationFt": "1,350–3,350 ft",
    "surface": "Graded-to-rocky ridge road",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S07 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Overlooks of Lake Elsinore",
      "Smoother companion to the north divide",
      "Chaparral ridgetop scenery (plated only)"
    ],
    "trailhead": {
      "name": "South Main Divide Road (6S07)",
      "lat": 33.6164,
      "lng": -117.3541
    }
  },
  {
    "id": "maple-springs",
    "name": "Maple Springs Road",
    "forestRoad": "5S04",
    "summary": "Climbs from Silverado Canyon up to the Main Divide.",
    "description": "Maple Springs Road (5S04) climbs out of Silverado Canyon through oak and bay woodland to meet the Main Divide near Modjeska Peak. A scenic graded-to-rocky climb and one of the main ways up to the crest from the Orange County side, highway-legal only.",
    "distanceMiles": 7.3,
    "difficulty": "Moderate",
    "elevationFt": "1,850–4,500 ft",
    "surface": "Graded dirt with rocky upper sections",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 5S04 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Shaded climb out of Silverado Canyon",
      "Connects to the Main Divide crest",
      "Oak-and-bay woodland (plated only)"
    ],
    "trailhead": {
      "name": "Maple Springs Road (5S04)",
      "lat": 33.7471,
      "lng": -117.584
    }
  },
  {
    "id": "indian-truck-trail",
    "name": "Indian Truck Trail",
    "forestRoad": "5S01",
    "summary": "Long graded climb to the divide from the Corona side.",
    "description": "Indian Truck Trail (5S01) climbs the eastern flank of the Santa Anas from the Corona / Lake Mathews side up to the Main Divide, a steady graded ascent through chaparral with expanding Inland Empire views. A popular plated dual-sport climb, highway-legal only.",
    "distanceMiles": 7.1,
    "difficulty": "Moderate",
    "elevationFt": "1,300–3,750 ft",
    "surface": "Graded dirt, steady grade",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 5S01 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Long steady climb to the crest",
      "Inland Empire views",
      "Popular plated dual-sport route"
    ],
    "trailhead": {
      "name": "Indian Truck Trail (5S01)",
      "lat": 33.7422,
      "lng": -117.4588
    }
  },
  {
    "id": "trabuco-canyon",
    "name": "Trabuco Canyon Road",
    "forestRoad": "6S13",
    "summary": "Rough, rocky canyon road to the Holy Jim trailhead.",
    "description": "Trabuco Canyon Road (6S13) runs up the boulder-strewn Trabuco Canyon to the Holy Jim trailhead, a notoriously rocky, rutted, creek-crossing road that demands real high-clearance riding. Short but technical, shaded and scenic, highway-legal only.",
    "distanceMiles": 3.2,
    "difficulty": "Difficult",
    "elevationFt": "1,300–2,050 ft",
    "surface": "Rocky, rutted canyon road with creek crossings",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S13 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Rough, technical canyon riding",
      "Shaded Trabuco Canyon and Holy Jim",
      "Short but demanding (plated only)"
    ],
    "trailhead": {
      "name": "Trabuco Canyon Road (6S13)",
      "lat": 33.6718,
      "lng": -117.5522
    }
  },
  {
    "id": "bedford-ridge",
    "name": "Bedford Ridge Road",
    "forestRoad": "4S03",
    "summary": "Short ridge spur off the northern divide country.",
    "description": "Bedford Ridge (4S03) is a shorter high-clearance ridge road in the northern Santa Anas, mixing rocky benches and chaparral with valley views. A compact plated ride best linked with the Main Divide, highway-legal only.",
    "distanceMiles": 3.5,
    "difficulty": "Moderate",
    "elevationFt": "2,100–3,700 ft",
    "surface": "Rocky high-clearance ridge dirt",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 4S03 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Compact northern-divide spur",
      "Chaparral ridge and valley views",
      "Pairs with the Main Divide (plated only)"
    ],
    "trailhead": {
      "name": "Bedford Ridge Road (4S03)",
      "lat": 33.7948,
      "lng": -117.5374
    }
  },
  {
    "id": "long-canyon",
    "name": "Long Canyon Road",
    "forestRoad": "6S05",
    "summary": "Mellow graded road in the El Cariso / Blue Jay area.",
    "description": "Long Canyon Road (6S05) is a gentler graded road around the El Cariso and Blue Jay campground area on the south end of the range, good for an easy plated cruise and reaching trailheads and camps. Highway-legal only.",
    "distanceMiles": 3.4,
    "difficulty": "Easy",
    "elevationFt": "2,400–3,400 ft",
    "surface": "Wide graded dirt, generally smooth",
    "bestSeason": "Year-round (avoid heat and after rain)",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 6S05 is open to highway-legal vehicles only: plated, street-legal bikes only, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Easy graded riding near Blue Jay / El Cariso",
      "Campground and trailhead access",
      "Beginner-friendly plated route"
    ],
    "trailhead": {
      "name": "Long Canyon Road (6S05)",
      "lat": 33.6375,
      "lng": -117.4221
    }
  }
];
