// AUTO-GENERATED by scripts/build-area-routes.mjs — do not edit by hand.
// Geometry & access: USFS MVUM (EDW_MVUM_01). Elevation: SRTM via opentopodata.
// Prose, difficulty, and ordering are editorial (see the script's CONFIG).
import type { Route } from "../types";

export const santaBarbaraRoutes: Route[] = [
  {
    "id": "camuesa-road",
    "name": "Camuesa Road (Romero–Camuesa)",
    "forestRoad": "5N15.2",
    "summary": "The backbone of Santa Barbara's Camuesa OHV area, green-sticker riding.",
    "description": "The Romero–Camuesa road (5N15) is the spine of the Camuesa OHV area in the Santa Ynez backcountry, with segment 5N15.2 designated open to all vehicles. It's a rugged, remote backcountry road through chaparral and oak, the heart of the only real green-sticker network near Santa Barbara, with seasonal wet-weather closures.",
    "distanceMiles": 11.8,
    "difficulty": "Difficult",
    "elevationFt": "1,250–2,800 ft",
    "surface": "Rugged backcountry dirt with rocky, eroded sections",
    "bestSeason": "Late spring–fall (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5N15.2 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Core of the Camuesa OHV area",
      "Designated green-sticker (open to all vehicles)",
      "Remote Santa Ynez backcountry"
    ],
    "trailhead": {
      "name": "Camuesa Road (Romero–Camuesa) (5N15.2)",
      "lat": 34.5418,
      "lng": -119.6589
    }
  },
  {
    "id": "east-camino-cielo",
    "name": "East Camino Cielo (OHV segment)",
    "forestRoad": "5N12.1",
    "summary": "The legendary ridge road above Santa Barbara, its OHV-open stretch.",
    "description": "East Camino Cielo rides the crest of the Santa Ynez Mountains directly above Santa Barbara, with the 5N12.1 segment designated open to all vehicles. Expect knife-edge ocean-and-backcountry views, sandstone outcrops, and a mix of graded and rougher tread along one of the most scenic ridgelines in the county.",
    "distanceMiles": 11.9,
    "difficulty": "Moderate",
    "elevationFt": "2,750–4,600 ft",
    "surface": "Mixed graded dirt and rocky sandstone tread",
    "bestSeason": "Spring–fall (seasonal closures when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 5N12.1 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Crest-of-the-range ocean and backcountry views",
      "Sandstone outcrops along the ridge",
      "Green-sticker-open ridge segment"
    ],
    "trailhead": {
      "name": "East Camino Cielo (OHV segment) (5N12.1)",
      "lat": 34.4796,
      "lng": -119.4388
    }
  },
  {
    "id": "buckhorn-road",
    "name": "Buckhorn Road",
    "forestRoad": "9N11.4",
    "summary": "Remote green-sticker road into the San Rafael backcountry.",
    "description": "9N11.4 (Buckhorn) pushes into the remote San Rafael / upper Santa Ynez backcountry as a designated road open to all vehicles. It's a long, rugged, lightly-traveled high-clearance route through chaparral and pine, proper green-sticker backcountry with seasonal closures, so go prepared and self-sufficient.",
    "distanceMiles": 10.1,
    "difficulty": "Difficult",
    "elevationFt": "2,800–4,750 ft",
    "surface": "Rugged high-clearance dirt; rough and remote",
    "bestSeason": "Late spring–fall (closed when wet)",
    "access": {
      "streetLegal": true,
      "greenSticker": "yes",
      "note": "Per the MVUM, 9N11.4 is designated open to all vehicles, so green-sticker (non-street-legal) bikes are allowed. Registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Deep San Rafael backcountry",
      "Designated green-sticker road",
      "Quiet, remote, and rugged"
    ],
    "trailhead": {
      "name": "Buckhorn Road (9N11.4)",
      "lat": 34.6361,
      "lng": -119.7135
    }
  },
  {
    "id": "zaca-ridge",
    "name": "Zaca Ridge OHV Road",
    "forestRoad": "8N02",
    "summary": "Ridge road in the Zaca Peak OHV area, green-sticker on part of it.",
    "description": "8N02 climbs to Zaca Ridge in the Zaca Peak OHV area north of the Santa Ynez Valley. Rolling chaparral ridgetops, oak woodland, and big views over the wine-country valleys make it one of the more approachable rides in the forest. Part of the road is open to all vehicles, with green-sticker access changing by segment, and it's open seasonally.",
    "distanceMiles": 7.6,
    "difficulty": "Moderate",
    "elevationFt": "3,450–4,200 ft",
    "surface": "Graded-to-rocky ridge road",
    "bestSeason": "Spring–fall (seasonal)",
    "access": {
      "streetLegal": true,
      "greenSticker": "partial",
      "note": "Per the MVUM, Zaca Ridge OHV Road is mixed: some segments are open to all vehicles (green-sticker OK) and others are open to street-legal vehicles only, so access goes segment by segment. Read the signs at each junction; registration + spark arrestor required. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Green-sticker access on part of the road (seasonal)",
      "Chaparral ridgetops and oak woodland",
      "Views over the Santa Ynez wine country"
    ],
    "trailhead": {
      "name": "Zaca Ridge OHV Road (8N02)",
      "lat": 34.7363,
      "lng": -119.9961
    }
  },
  {
    "id": "west-dry-canyon",
    "name": "West Dry Canyon Road",
    "forestRoad": "8N19",
    "summary": "Quiet plated backcountry road in the Sunset Valley area.",
    "description": "8N19 runs through the West Dry Canyon / Sunset Valley country as a road open to street-legal vehicles only. It's a quiet, scenic plated dual-sport ride through oak and chaparral with creek crossings, a good way to link the area's backcountry without the technical demands of the OHV roads.",
    "distanceMiles": 7.9,
    "difficulty": "Moderate",
    "elevationFt": "3,250–5,800 ft",
    "surface": "Graded dirt with creek crossings",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 8N19 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Quiet oak-and-chaparral backcountry",
      "Seasonal creek crossings",
      "Scenic plated dual-sport route"
    ],
    "trailhead": {
      "name": "West Dry Canyon Road (8N19)",
      "lat": 34.7855,
      "lng": -119.5718
    }
  },
  {
    "id": "sunset-valley-road",
    "name": "Sunset Valley Road",
    "forestRoad": "8N09",
    "summary": "Mellow plated road into the Sunset Valley backcountry.",
    "description": "8N09 is a gentler graded road into the Sunset Valley area, a relaxed plated ride good for easy miles and reaching trailheads and dispersed camps. Oak woodland, open valley, and easy navigation. Open to street-legal vehicles only.",
    "distanceMiles": 5.7,
    "difficulty": "Easy",
    "elevationFt": "1,800–3,100 ft",
    "surface": "Wide graded dirt, generally smooth",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 8N09 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Easy, beginner-friendly grade",
      "Oak woodland and open valley",
      "Access to dispersed camping (plated only)"
    ],
    "trailhead": {
      "name": "Sunset Valley Road (8N09)",
      "lat": 34.7269,
      "lng": -119.9196
    }
  },
  {
    "id": "happy-canyon-road",
    "name": "Happy Canyon Road",
    "forestRoad": "7N07.2",
    "summary": "Scenic plated road from the Santa Ynez Valley into the forest.",
    "description": "Happy Canyon (7N07) climbs from the Santa Ynez Valley up into the Los Padres backcountry, transitioning from oak-dotted ranch country to chaparral forest. A long, scenic road for street-legal bikes only, a classic plated dual-sport climb toward Figueroa Mountain country.",
    "distanceMiles": 9.8,
    "difficulty": "Moderate",
    "elevationFt": "2,450–4,450 ft",
    "surface": "Graded dirt, smooth lower, rougher up high",
    "bestSeason": "Spring–fall",
    "access": {
      "streetLegal": true,
      "greenSticker": "no",
      "note": "Per the MVUM, 7N07.2 is open to street-legal vehicles only: plated bikes, no green-sticker (non-street-legal) bikes. This route has a seasonal (wet-weather) closure, so confirm it's open before you go.",
      "source": "USFS Motor Vehicle Use Map (MVUM), 2026"
    },
    "highlights": [
      "Santa Ynez Valley to forest transition",
      "Toward Figueroa Mountain country",
      "Long scenic plated climb"
    ],
    "trailhead": {
      "name": "Happy Canyon Road (7N07.2)",
      "lat": 34.7428,
      "lng": -120.029
    }
  }
];
